version: '3.5'

services:
  mongodb:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017

  server:
    build:
      context: ./server
      dockerfile: "Dockerfile"
    hostname: editorserver
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongodb:27017
    depends_on:
      - mongodb
    ports:
      - 8000:8000

  client:
    build:
      context: ./client
      dockerfile: "Dockerfile"
    hostname: editorclient
    depends_on:
      - server
    ports:
      - 3000:3000
